# render.yaml
services:
  - type: web
    name: music-mind
    env: python
    buildCommand: |
      pip install -r requirements.txt 
      python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app
